# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
 # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
name: journal_cubit
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  # Updated Firebase versions to match latest stable releases
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  flutter_cache_manager: ^3.3.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  google_sign_in: ^6.1.0
  meta: ^1.8.0
  get_it: ^7.6.7
  uuid: ^4.4.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/uche_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/uche_logo.png