// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB74461NBxHfP5xC7qFm4F8Jvz9ZtLZJ9E',
    appId: '1:654467094275:web:7961cbf0005c9e53007b36',
    messagingSenderId: '654467094275',
    projectId: 'four-quarters-journaling',
    authDomain: 'four-quarters-journaling.firebaseapp.com',
    storageBucket: 'four-quarters-journaling.appspot.com',
    measurementId: 'G-XQ23TYVX03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIkKhwDNbLSe3CtUyJrCDlwEqTeUdHetI',
    appId: '1:654467094275:android:c746b9a2a4eaab35007b36',
    messagingSenderId: '654467094275',
    projectId: 'four-quarters-journaling',
    storageBucket: 'four-quarters-journaling.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLjz-698LIhvW3r6MkKXPN6rh4et-77T0',
    appId: '1:654467094275:ios:53354dcfc1ebe747007b36',
    messagingSenderId: '654467094275',
    projectId: 'four-quarters-journaling',
    storageBucket: 'four-quarters-journaling.appspot.com',
    iosBundleId: 'com.jmagic.journalCubit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLjz-698LIhvW3r6MkKXPN6rh4et-77T0',
    appId: '1:654467094275:ios:7681c0071b99a21e007b36',
    messagingSenderId: '654467094275',
    projectId: 'four-quarters-journaling',
    storageBucket: 'four-quarters-journaling.appspot.com',
    iosBundleId: 'com.jmagic.journalCubit.RunnerTests',
  );
}
